site_name: Documentación de desarrollo
nav:
    - Home: index.md
    - Guías de instalación de entorno:       
        - LAMP: lamp/index.md 
        - HestiaCP (Debian 9): hestiacp/index.md 
        - Tomacat 8 (Debian 9): tomcat/index.md 
theme: readthedocs
site_dir: ../../docs
