site_name: Documentaci√≥n de desarrollo
nav:
    - Home: index.md
    - lamp/index.md
    - hestiacp/index.md 
    - piecesphp/index.md
    - tomcat/index.md 
theme:
    name: material
    language: es
    palette:
        scheme: slate
        primary: black
        accent: red
site_dir: ../../docs



